### ISSUE TITLE
elasticsearch implementation

### ISSUE THREAD

**Issue by wunderszindi** [flowacademyhu/epsilon-my-favorite-expert#10]
Elasticsearch implementálása Springbe.
User Document létrehozása, updattel és lekérdezéssel.

**Comment by hajnalandor** [comment]
Ilyen formátumban tárolhatjuk a felhasználókat?
user {  id:
           name:
          provider: [ { gmail: { email::
                                          image_url:
                                          provider_id:
                                       }
                             }]
         acces_token:
         create_at:
         expire_at:
         isdeleted:
}

**Comment by hajnalandor** [comment]
Deserializálási problémába ütköztünk, ami akkor keletkezik, amikor updatelni akarjuk a usert. Ezt próbáljuk ma orvosolni.

**Comment by PumpkinSeed** [comment]
Resolved in #22
