### ISSUE TITLE
Expertek kezelese

### ISSUE THREAD

**Issue by PumpkinSeed** [flowacademyhu/epsilon-my-favorite-expert#25]
- [x] Lehessen szavakat (keyword) megadva szűrni a szolgáltatók listáját
- [x] Kapcsolatra szűkíteni (szűrni) a szolgáltatók listáját
- [x] A keyword megadás legyen prediktív - egészítse ki a legvalószínűbbre
- [x] A listában jelenítsük meg a szolgáltató regisztrált telephelyétől való távolságot is (légvonalban)
- [x] A listát lehessen rendezni két irányban, név és távolság alapján
- [ ] Tudjak távolság alapján is szűrni (max. távolság)
- [ ] Az oldal jegyezze meg az utolsó beállításaimat

**Comment by borosr** [comment]
> A keyword megadás legyen prediktív - egészítse ki a legvalószínűbbre
A szűrés során számolunk az elgépelésekkel, azonban a frontenden nincs autocomplete vagy egyéb segítség
