### ISSUE TITLE
0.2 verzió igények

### ISSUE THREAD

**Issue by borosr** [flowacademyhu/epsilon-my-favorite-expert#7]
* Legyen egy lista amivel listázhatóak a cégek   
* legyek képes megjelölni a listából a kedvenc szakembereimet   
* legyen megjelölve a lista elemek közül a kedvenceim  
* tudjak szűrni, hogy csak a kedvenceimet lássam   
* Legyél képes levenni a kedvenc jelölést

**Comment by PumpkinSeed** [comment]
Feature ami meg v0.2.0-ben lesz:
- Profile, cim felvetele
- Expert felvetele

**Comment by PumpkinSeed** [comment]
All resolved in #22
